#生产环境的配置
server:
  port: 80
debug: false
spring:
  profiles: pro
  datasource:
    #指定使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/easyblog?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 95162437hx$
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-password: 123456
        login-username: Admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        exclusions: .js,.css,.html,/druid/*
        url-pattern: /*
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,logback
      # 初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭,如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: redis      #在docker容器中部署，host地址一定要写你配置的Redis容器的名字
    port: 6379
    database: 0
    password: CySynWsw5NLzbzHne3XcXaRGPWKpJxSKsHikLYvQ6VI0dNKjScuyYPjt
    timeout: 10000
    lettuce:
      pool:
        max-active: 8       # 连接池最大连接数，使用负值表示没有限制
        max-wait: -1        # 连接池最大阻塞等待时间，默认是负值表示无限等待
        max-idle: 5         # 连接池的最大空闲连接
        min-idle: 0         # 连接池的最小空闲连接
      shutdown-timeout: 1200           # 连接超时时间(ms)
  thymeleaf:
    cache: false
#第三方认证
oauth:
  github:
    client-id: 2357d5a950e31f627374
    client-secret: 4218dc574e0a2414f0719fc18e616305358aa7be
    redirectUrl: https://www.easyblog.top/oauth/github/callback
logging:
  level:
    root: info
    top.easyblog.mapper: DEBUG
  file: easyblog-pro.log