#开发环境
server:
  port: 8081
debug: true
spring:
  profiles: dev
  datasource:
    #指定使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.234.128:3306/easyblog?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: aaaaaa
    #password: huangxin@95162437
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-password: 123456
        login-username: Admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        exclusions: .js,.css,.html,/druid/*
        url-pattern: /*
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,logback
      # 初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭,如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
  #热部署配置
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java
  redis:
    host: 192.168.234.128
    port: 6379
    password: aaaaaa
    database: 0
    timeout: 10000
    #springBoot 2.x应该配置lettuce作为Redis客户端  Spring1.x配置jedis
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 5000ms
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  #第三方认证
oauth:
 github:
   client-id: 2d3eaf3a6c76b636e891
   client-secret: d81730cc534c9cc59990625e4d9f573c34bfb499
   redirectUrl: http://127.0.0.1:8081/oauth/github/callback
#日志
logging:
  level:
    root: debug
    top.easyblog: debug
  file: easyblog-dev.log